USE [master]
GO

/****** Object:  Database [GreenNursery]    Script Date: 28/07/2019 10:06:22 p. m. ******/
CREATE DATABASE [GreenNursery]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GreenNursery', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\GreenNursery.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GreenNursery_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\GreenNursery_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GreenNursery] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GreenNursery].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GreenNursery] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GreenNursery] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GreenNursery] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GreenNursery] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GreenNursery] SET ARITHABORT OFF 
GO

ALTER DATABASE [GreenNursery] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GreenNursery] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [GreenNursery] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GreenNursery] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GreenNursery] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GreenNursery] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GreenNursery] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GreenNursery] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GreenNursery] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GreenNursery] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GreenNursery] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GreenNursery] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GreenNursery] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GreenNursery] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GreenNursery] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GreenNursery] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GreenNursery] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GreenNursery] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GreenNursery] SET RECOVERY FULL 
GO

ALTER DATABASE [GreenNursery] SET  MULTI_USER 
GO

ALTER DATABASE [GreenNursery] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GreenNursery] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GreenNursery] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GreenNursery] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GreenNursery] SET  READ_WRITE 
GO

